# Computes and saves the results for the natural and stochastic grace period strategies with m=3.
# See './src/functions.R' for further details

source('./src/dependencies.R')
source('./src/functions.R')

load('cohort.RData')

save_results_ACE_natural_m_3 <- 
  resultsfnc(initiated_treatment = 'ACE',
             data = cohort,
             pooled_time_treatment_model = F,
             skip_first_interval = T,
             max_interval = NULL,
             grace_period_length = 3,
             f_int = NULL,
             f_cond_int = NULL,
             vars_to_lag_trt = c('bariatric',
                                 'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_trt = 5,
             model_formula_vars_trt = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                        'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                        'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_trt = F,
             nfold_trt = 5,
             tree_depth_trt = seq(1,5,1),
             shrinkage_factor_trt = seq(0.01,0.1,0.01),
             num_trees_trt = seq(100,500,50),
             num_cores_trt = 5,
             parametric_outcome_non_DR = NULL,
             model_formula_vars_censoring = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                              'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                              'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_censoring = F,
             nfold_censoring = 5,
             tree_depth_censoring = seq(1,5,1),
             shrinkage_factor_censoring = seq(0.01,0.1,0.01),
             num_trees_censoring = seq(100,500,50),
             num_cores_censoring = 5,
             vars_to_lag_outcome = c('bariatric',
                                     'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_outcome = 5,
             model_formula_vars_outcome = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                            'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                            'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_outcome = F,
             nfold_outcome = 5,
             tree_depth_outcome = seq(1,5,1),
             shrinkage_factor_outcome = seq(0.01,0.1,0.01),
             num_trees_outcome = seq(100,500,50),
             num_cores_outcome = 5,
             nsplits = 2,
             DR = T)

save(save_results_ACE_natural_m_3, file='save_results_ACE_natural_m_3.Rdata')

###########################################################################################################

save_results_thiazide_natural_m_3 <- 
  resultsfnc(initiated_treatment = 'thiazide',
             data = cohort,
             pooled_time_treatment_model = F,
             skip_first_interval = T,
             max_interval = NULL,
             grace_period_length = 3,
             f_int = NULL,
             f_cond_int = NULL,
             vars_to_lag_trt = c('bariatric',
                                 'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_trt = 5,
             model_formula_vars_trt = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                        'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                        'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_trt = F,
             nfold_trt = 5,
             tree_depth_trt = seq(1,5,1),
             shrinkage_factor_trt = seq(0.01,0.1,0.01),
             num_trees_trt = seq(100,500,50),
             num_cores_trt = 5,
             parametric_outcome_non_DR = NULL,
             model_formula_vars_censoring = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                              'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                              'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_censoring = F,
             nfold_censoring = 5,
             tree_depth_censoring = seq(1,5,1),
             shrinkage_factor_censoring = seq(0.01,0.1,0.01),
             num_trees_censoring = seq(100,500,50),
             num_cores_censoring = 5,
             vars_to_lag_outcome = c('bariatric',
                                     'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_outcome = 5,
             model_formula_vars_outcome = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                            'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                            'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_outcome = F,
             nfold_outcome = 5,
             tree_depth_outcome = seq(1,5,1),
             shrinkage_factor_outcome = seq(0.01,0.1,0.01),
             num_trees_outcome = seq(100,500,50),
             num_cores_outcome = 5,
             nsplits = 2,
             DR = T)

save(save_results_thiazide_natural_m_3, file='save_results_thiazide_natural_m_3.Rdata')

###########################################################################################################
###########################################################################################################
###########################################################################################################

save_results_ACE_stochastic_0.5_constant_m_3 <- 
  resultsfnc(initiated_treatment = 'ACE',
             data = cohort,
             pooled_time_treatment_model = F,
             skip_first_interval = T,
             max_interval = NULL,
             grace_period_length = 3,
             f_int = NULL,
             f_cond_int = c(0.5, 0.5, 0.5),
             vars_to_lag_trt = c('bariatric',
                                 'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_trt = 5,
             model_formula_vars_trt = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                        'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                        'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_trt = F,
             nfold_trt = 5,
             tree_depth_trt = seq(1,5,1),
             shrinkage_factor_trt = seq(0.01,0.1,0.01),
             num_trees_trt = seq(100,500,50),
             num_cores_trt = 5,
             parametric_outcome_non_DR = NULL,
             model_formula_vars_censoring = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                              'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                              'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_censoring = F,
             nfold_censoring = 5,
             tree_depth_censoring = seq(1,5,1),
             shrinkage_factor_censoring = seq(0.01,0.1,0.01),
             num_trees_censoring = seq(100,500,50),
             num_cores_censoring = 5,
             vars_to_lag_outcome = c('bariatric',
                                     'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_outcome = 5,
             model_formula_vars_outcome = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                            'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                            'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_outcome = F,
             nfold_outcome = 5,
             tree_depth_outcome = seq(1,5,1),
             shrinkage_factor_outcome = seq(0.01,0.1,0.01),
             num_trees_outcome = seq(100,500,50),
             num_cores_outcome = 5,
             nsplits = 2,
             DR = T)

save(save_results_ACE_stochastic_0.5_constant_m_3, file='save_results_ACE_stochastic_0.5_constant_m_3.Rdata')

###########################################################################################################

save_results_thiazide_stochastic_0.5_constant_m_3 <- 
  resultsfnc(initiated_treatment = 'thiazide',
             data = cohort,
             pooled_time_treatment_model = F,
             skip_first_interval = T,
             max_interval = NULL,
             grace_period_length = 3,
             f_int = NULL,
             f_cond_int = c(0.5, 0.5, 0.5),
             vars_to_lag_trt = c('bariatric',
                                 'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_trt = 5,
             model_formula_vars_trt = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                        'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                        'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_trt = F,
             nfold_trt = 5,
             tree_depth_trt = seq(1,5,1),
             shrinkage_factor_trt = seq(0.01,0.1,0.01),
             num_trees_trt = seq(100,500,50),
             num_cores_trt = 5,
             parametric_outcome_non_DR = NULL,
             model_formula_vars_censoring = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                              'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                              'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_censoring = F,
             nfold_censoring = 5,
             tree_depth_censoring = seq(1,5,1),
             shrinkage_factor_censoring = seq(0.01,0.1,0.01),
             num_trees_censoring = seq(100,500,50),
             num_cores_censoring = 5,
             vars_to_lag_outcome = c('bariatric',
                                     'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_outcome = 5,
             model_formula_vars_outcome = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                            'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                            'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_outcome = F,
             nfold_outcome = 5,
             tree_depth_outcome = seq(1,5,1),
             shrinkage_factor_outcome = seq(0.01,0.1,0.01),
             num_trees_outcome = seq(100,500,50),
             num_cores_outcome = 5,
             nsplits = 2,
             DR = T)

save(save_results_thiazide_stochastic_0.5_constant_m_3, file='save_results_thiazide_stochastic_0.5_constant_m_3.Rdata')

###########################################################################################################
###########################################################################################################
###########################################################################################################

save_results_ACE_stochastic_0.75_constant_m_3 <- 
  resultsfnc(initiated_treatment = 'ACE',
             data = cohort,
             pooled_time_treatment_model = F,
             skip_first_interval = T,
             max_interval = NULL,
             grace_period_length = 3,
             f_int = NULL,
             f_cond_int = c(0.75, 0.75, 0.75),
             vars_to_lag_trt = c('bariatric',
                                 'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_trt = 5,
             model_formula_vars_trt = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                        'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                        'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_trt = F,
             nfold_trt = 5,
             tree_depth_trt = seq(1,5,1),
             shrinkage_factor_trt = seq(0.01,0.1,0.01),
             num_trees_trt = seq(100,500,50),
             num_cores_trt = 5,
             parametric_outcome_non_DR = NULL,
             model_formula_vars_censoring = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                              'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                              'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_censoring = F,
             nfold_censoring = 5,
             tree_depth_censoring = seq(1,5,1),
             shrinkage_factor_censoring = seq(0.01,0.1,0.01),
             num_trees_censoring = seq(100,500,50),
             num_cores_censoring = 5,
             vars_to_lag_outcome = c('bariatric',
                                     'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_outcome = 5,
             model_formula_vars_outcome = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                            'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                            'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_outcome = F,
             nfold_outcome = 5,
             tree_depth_outcome = seq(1,5,1),
             shrinkage_factor_outcome = seq(0.01,0.1,0.01),
             num_trees_outcome = seq(100,500,50),
             num_cores_outcome = 5,
             nsplits = 2,
             DR = T)

save(save_results_ACE_stochastic_0.75_constant_m_3, file='save_results_ACE_stochastic_0.75_constant_m_3.Rdata')

###########################################################################################################

save_results_thiazide_stochastic_0.75_constant_m_3 <- 
  resultsfnc(initiated_treatment = 'thiazide',
             data = cohort,
             pooled_time_treatment_model = F,
             skip_first_interval = T,
             max_interval = NULL,
             grace_period_length = 3,
             f_int = NULL,
             f_cond_int = c(0.75, 0.75, 0.75),
             vars_to_lag_trt = c('bariatric',
                                 'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_trt = 5,
             model_formula_vars_trt = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                        'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                        'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_trt = F,
             nfold_trt = 5,
             tree_depth_trt = seq(1,5,1),
             shrinkage_factor_trt = seq(0.01,0.1,0.01),
             num_trees_trt = seq(100,500,50),
             num_cores_trt = 5,
             parametric_outcome_non_DR = NULL,
             model_formula_vars_censoring = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                              'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                              'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_censoring = F,
             nfold_censoring = 5,
             tree_depth_censoring = seq(1,5,1),
             shrinkage_factor_censoring = seq(0.01,0.1,0.01),
             num_trees_censoring = seq(100,500,50),
             num_cores_censoring = 5,
             vars_to_lag_outcome = c('bariatric',
                                     'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_outcome = 5,
             model_formula_vars_outcome = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                            'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                            'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_outcome = F,
             nfold_outcome = 5,
             tree_depth_outcome = seq(1,5,1),
             shrinkage_factor_outcome = seq(0.01,0.1,0.01),
             num_trees_outcome = seq(100,500,50),
             num_cores_outcome = 5,
             nsplits = 2,
             DR = T)

save(save_results_thiazide_stochastic_0.75_constant_m_3, file='save_results_thiazide_stochastic_0.75_constant_m_3.Rdata')

###########################################################################################################
###########################################################################################################
###########################################################################################################

save_results_ACE_stochastic_0.9_constant_m_3 <- 
  resultsfnc(initiated_treatment = 'ACE',
             data = cohort,
             pooled_time_treatment_model = F,
             skip_first_interval = T,
             max_interval = NULL,
             grace_period_length = 3,
             f_int = NULL,
             f_cond_int = c(0.9, 0.9, 0.9),
             vars_to_lag_trt = c('bariatric',
                                 'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_trt = 5,
             model_formula_vars_trt = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                        'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                        'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_trt = F,
             nfold_trt = 5,
             tree_depth_trt = seq(1,5,1),
             shrinkage_factor_trt = seq(0.01,0.1,0.01),
             num_trees_trt = seq(100,500,50),
             num_cores_trt = 5,
             parametric_outcome_non_DR = NULL,
             model_formula_vars_censoring = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                              'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                              'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_censoring = F,
             nfold_censoring = 5,
             tree_depth_censoring = seq(1,5,1),
             shrinkage_factor_censoring = seq(0.01,0.1,0.01),
             num_trees_censoring = seq(100,500,50),
             num_cores_censoring = 5,
             vars_to_lag_outcome = c('bariatric',
                                     'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_outcome = 5,
             model_formula_vars_outcome = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                            'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                            'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_outcome = F,
             nfold_outcome = 5,
             tree_depth_outcome = seq(1,5,1),
             shrinkage_factor_outcome = seq(0.01,0.1,0.01),
             num_trees_outcome = seq(100,500,50),
             num_cores_outcome = 5,
             nsplits = 2,
             DR = T)

save(save_results_ACE_stochastic_0.9_constant_m_3, file='save_results_ACE_stochastic_0.9_constant_m_3.Rdata')

###########################################################################################################

save_results_thiazide_stochastic_0.9_constant_m_3 <- 
  resultsfnc(initiated_treatment = 'thiazide',
             data = cohort,
             pooled_time_treatment_model = F,
             skip_first_interval = T,
             max_interval = NULL,
             grace_period_length = 3,
             f_int = NULL,
             f_cond_int = c(0.9, 0.9, 0.9),
             vars_to_lag_trt = c('bariatric',
                                 'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_trt = 5,
             model_formula_vars_trt = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                        'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                        'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_trt = F,
             nfold_trt = 5,
             tree_depth_trt = seq(1,5,1),
             shrinkage_factor_trt = seq(0.01,0.1,0.01),
             num_trees_trt = seq(100,500,50),
             num_cores_trt = 5,
             parametric_outcome_non_DR = NULL,
             model_formula_vars_censoring = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                              'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                              'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_censoring = F,
             nfold_censoring = 5,
             tree_depth_censoring = seq(1,5,1),
             shrinkage_factor_censoring = seq(0.01,0.1,0.01),
             num_trees_censoring = seq(100,500,50),
             num_cores_censoring = 5,
             vars_to_lag_outcome = c('bariatric',
                                     'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_outcome = 5,
             model_formula_vars_outcome = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                            'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                            'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_outcome = F,
             nfold_outcome = 5,
             tree_depth_outcome = seq(1,5,1),
             shrinkage_factor_outcome = seq(0.01,0.1,0.01),
             num_trees_outcome = seq(100,500,50),
             num_cores_outcome = 5,
             nsplits = 2,
             DR = T)

save(save_results_thiazide_stochastic_0.9_constant_m_3, file='save_results_thiazide_stochastic_0.9_constant_m_3.Rdata')

###########################################################################################################
###########################################################################################################
###########################################################################################################

save_results_ACE_stochastic_0.95_constant_m_3 <- 
  resultsfnc(initiated_treatment = 'ACE',
             data = cohort,
             pooled_time_treatment_model = F,
             skip_first_interval = T,
             max_interval = NULL,
             grace_period_length = 3,
             f_int = NULL,
             f_cond_int = c(0.95, 0.95, 0.95),
             vars_to_lag_trt = c('bariatric',
                                 'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_trt = 5,
             model_formula_vars_trt = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                        'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                        'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_trt = F,
             nfold_trt = 5,
             tree_depth_trt = seq(1,5,1),
             shrinkage_factor_trt = seq(0.01,0.1,0.01),
             num_trees_trt = seq(100,500,50),
             num_cores_trt = 5,
             parametric_outcome_non_DR = NULL,
             model_formula_vars_censoring = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                              'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                              'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_censoring = F,
             nfold_censoring = 5,
             tree_depth_censoring = seq(1,5,1),
             shrinkage_factor_censoring = seq(0.01,0.1,0.01),
             num_trees_censoring = seq(100,500,50),
             num_cores_censoring = 5,
             vars_to_lag_outcome = c('bariatric',
                                     'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_outcome = 5,
             model_formula_vars_outcome = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                            'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                            'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_outcome = F,
             nfold_outcome = 5,
             tree_depth_outcome = seq(1,5,1),
             shrinkage_factor_outcome = seq(0.01,0.1,0.01),
             num_trees_outcome = seq(100,500,50),
             num_cores_outcome = 5,
             nsplits = 2,
             DR = T)

save(save_results_ACE_stochastic_0.95_constant_m_3, file='save_results_ACE_stochastic_0.95_constant_m_3.Rdata')

###########################################################################################################

save_results_thiazide_stochastic_0.95_constant_m_3 <- 
  resultsfnc(initiated_treatment = 'thiazide',
             data = cohort,
             pooled_time_treatment_model = F,
             skip_first_interval = T,
             max_interval = NULL,
             grace_period_length = 3,
             f_int = NULL,
             f_cond_int = c(0.95, 0.95, 0.95),
             vars_to_lag_trt = c('bariatric',
                                 'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_trt = 5,
             model_formula_vars_trt = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                        'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                        'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_trt = F,
             nfold_trt = 5,
             tree_depth_trt = seq(1,5,1),
             shrinkage_factor_trt = seq(0.01,0.1,0.01),
             num_trees_trt = seq(100,500,50),
             num_cores_trt = 5,
             parametric_outcome_non_DR = NULL,
             model_formula_vars_censoring = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                              'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                              'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_censoring = F,
             nfold_censoring = 5,
             tree_depth_censoring = seq(1,5,1),
             shrinkage_factor_censoring = seq(0.01,0.1,0.01),
             num_trees_censoring = seq(100,500,50),
             num_cores_censoring = 5,
             vars_to_lag_outcome = c('bariatric',
                                     'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             num_lags_outcome = 5,
             model_formula_vars_outcome = c('female', 'age', 'Chronic_Kidney_Disease_pre',
                                            'Liver_Cirrhosis_pre', 'T2D_pre', 'bariatric',
                                            'Chronic_Kidney_Disease', 'Liver_Cirrhosis', 'T2D', 'T1D'),
             parametric_model_outcome = F,
             nfold_outcome = 5,
             tree_depth_outcome = seq(1,5,1),
             shrinkage_factor_outcome = seq(0.01,0.1,0.01),
             num_trees_outcome = seq(100,500,50),
             num_cores_outcome = 5,
             nsplits = 2,
             DR = T)

save(save_results_thiazide_stochastic_0.95_constant_m_3, file='save_results_thiazide_stochastic_0.95_constant_m_3.Rdata')
